In [4]:
import numpy as np
A = [[1,2],[3,4]]
A

[[1, 2], [3, 4]]

In [14]:
np.max(A,-1)[np.newaxis,:]

array([[2, 4]])

In [15]:
B = A  - np.max(A,-1)[:,np.newaxis]

In [20]:
C = np.exp(B)
C

array([[ 0.36787944,  1.        ],
       [ 0.36787944,  1.        ]])

In [23]:
C = C / np.sum(C,1)[:,np.newaxis]

In [24]:
C

array([[ 0.26894142,  0.73105858],
       [ 0.26894142,  0.73105858]])

In [27]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
x[1:2,1:3]

array([[4, 5]])

In [35]:
np.arange(1,5)[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [39]:
print np.arange(5)
np.arange(5) % 4 == 1

[0 1 2 3 4]


array([False,  True, False, False, False], dtype=bool)

In [55]:
import glob
import os
import cPickle as pickle

In [43]:
f = glob.glob(r"saved_params_*.npy")

In [56]:
for i in f:
    print os.path.splitext(os.path.basename(i))[0].split("_")[2]

1000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
2000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
3000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
4000
40000
5000
6000
7000
8000
9000


In [59]:
index = int(os.path.splitext(os.path.basename(f[0]))[0].split("_")[2])
index

1000

In [63]:
with open(("saved_params_%d.npy") % index,"r") as f:
    params = pickle.load(f)
    state = pickle.load(f)

In [66]:
params

array([[  1.74236921e-02,  -2.99884954e-02,   3.05383125e-02, ...,
         -5.88958841e-02,   1.43836149e-02,   1.60465750e-02],
       [ -1.60591139e-02,  -5.71534151e-03,   2.63240284e-02, ...,
         -1.91368523e-03,   2.98162937e-02,   7.09594923e-03],
       [  5.83829067e-02,  -4.45471896e-02,  -1.63927915e-02, ...,
         -1.68284316e-02,   1.82358308e-03,  -9.14100498e-03],
       ..., 
       [ -5.04582980e-04,  -4.45873700e-04,  -1.85948361e-04, ...,
          2.09498066e-04,   7.78329045e-04,   2.54570111e-04],
       [ -1.31327422e-04,   1.79705821e-04,   2.37555938e-04, ...,
         -3.24732209e-04,  -2.46668513e-04,   2.53102957e-04],
       [ -2.55564421e-04,  -3.67629158e-04,   3.32448961e-04, ...,
         -8.29600834e-05,  -2.33844261e-04,  -2.95825969e-05]])

In [65]:
state

(3,
 (3660461006L,
  2290057391L,
  563193823L,
  2770880353L,
  163187524L,
  1815734899L,
  3075870360L,
  2316118318L,
  1134808463L,
  2373590459L,
  1768421817L,
  561948003L,
  1647186365L,
  2694055576L,
  3539250564L,
  2493659058L,
  2434703565L,
  838497199L,
  3613923968L,
  3199904546L,
  4275459354L,
  2065606934L,
  2075321675L,
  1240068755L,
  446303911L,
  1370003944L,
  1091131733L,
  2362863764L,
  3458455884L,
  48829034L,
  2300235711L,
  2259133745L,
  3993605L,
  4036098289L,
  1784765281L,
  3413758371L,
  1657463524L,
  1103619429L,
  1368782180L,
  2564232272L,
  396871277L,
  638562252L,
  693110819L,
  1052112535L,
  2002772943L,
  1465914451L,
  4098777882L,
  3631322591L,
  3987050843L,
  187315040L,
  3655810661L,
  3908006457L,
  2916922314L,
  1092019690L,
  4281632340L,
  2688178169L,
  1680486836L,
  702244746L,
  428404185L,
  405551498L,
  1299234666L,
  1182695257L,
  3070680604L,
  980765802L,
  3617457780L,
  2367233489L,
  1026682339L,
  1218366

In [67]:
import random

In [70]:
random.getstate()

(3,
 (3660461006L,
  2290057391L,
  563193823L,
  2770880353L,
  163187524L,
  1815734899L,
  3075870360L,
  2316118318L,
  1134808463L,
  2373590459L,
  1768421817L,
  561948003L,
  1647186365L,
  2694055576L,
  3539250564L,
  2493659058L,
  2434703565L,
  838497199L,
  3613923968L,
  3199904546L,
  4275459354L,
  2065606934L,
  2075321675L,
  1240068755L,
  446303911L,
  1370003944L,
  1091131733L,
  2362863764L,
  3458455884L,
  48829034L,
  2300235711L,
  2259133745L,
  3993605L,
  4036098289L,
  1784765281L,
  3413758371L,
  1657463524L,
  1103619429L,
  1368782180L,
  2564232272L,
  396871277L,
  638562252L,
  693110819L,
  1052112535L,
  2002772943L,
  1465914451L,
  4098777882L,
  3631322591L,
  3987050843L,
  187315040L,
  3655810661L,
  3908006457L,
  2916922314L,
  1092019690L,
  4281632340L,
  2688178169L,
  1680486836L,
  702244746L,
  428404185L,
  405551498L,
  1299234666L,
  1182695257L,
  3070680604L,
  980765802L,
  3617457780L,
  2367233489L,
  1026682339L,
  1218366

In [109]:
os.getcwd()

'/Users/weiyang/Project/NLPStanford/assignment2'

In [110]:
os.listdir("./")

['.DS_Store',
 '.ipynb_checkpoints',
 'assignment2.pdf',
 'collectSubmission.py',
 'data',
 'data_utils',
 'dev.predicted',
 'misc.py',
 'misc.pyc',
 'ner.learningcurve.best.png',
 'ner.learningcurve.comparison.png',
 'nerwindow.py',
 'nerwindow.pyc',
 'nn',
 'part0-XOR.ipynb',
 'part1-NER.ipynb',
 'part11probing.py',
 'part2-RNNLM.ipynb',
 'requirements.txt',
 'rnnlm.py',
 'rnnlm.pyc',
 'softmax_example.py',
 'softmax_example.pyc',
 'test.predicted']

In [83]:
random.setstate(state)
i = random.randint(0,3)
random.setstate(state)
j = f()
print i , j

2 2


In [108]:
os.chdir("/Users/weiyang/Project/NLPStanford/assignment2")

In [111]:
import data_utils.utils as du
import data_utils.ner as ner

In [121]:
vocabfile = 'data/ner/vocab.txt'
with open(vocabfile) as df:
    print df.readline()

UUUNKKK



In [123]:
wvfile = 'data/ner/wordVectors.txt'
wv = np.loadtxt(wvfile,dtype=float)

In [126]:
wv.shape
import re

In [127]:
fname = 'data/ner/train'
docs = []
with open(fname) as fd:
    cur = []
    for line in fd:
        # new sentence on -DOCSTART- or blank line
        if re.match(r"-DOCSTART-.+", line) or (len(line.strip()) == 0):
            if len(cur) > 0:
                docs.append(cur)
            cur = []
        else: # read in tokens
            cur.append(line.strip().split("\t",1))
        # flush running buffer
    docs.append(cur)

In [129]:
docs[0:10]

[[['EU', 'ORG'],
  ['rejects', 'O'],
  ['German', 'MISC'],
  ['call', 'O'],
  ['to', 'O'],
  ['boycott', 'O'],
  ['British', 'MISC'],
  ['lamb', 'O'],
  ['.', 'O']],
 [['Peter', 'PER'], ['Blackburn', 'PER']],
 [['BRUSSELS', 'LOC'], ['1996-08-22', 'O']],
 [['The', 'O'],
  ['European', 'ORG'],
  ['Commission', 'ORG'],
  ['said', 'O'],
  ['on', 'O'],
  ['Thursday', 'O'],
  ['it', 'O'],
  ['disagreed', 'O'],
  ['with', 'O'],
  ['German', 'MISC'],
  ['advice', 'O'],
  ['to', 'O'],
  ['consumers', 'O'],
  ['to', 'O'],
  ['shun', 'O'],
  ['British', 'MISC'],
  ['lamb', 'O'],
  ['until', 'O'],
  ['scientists', 'O'],
  ['determine', 'O'],
  ['whether', 'O'],
  ['mad', 'O'],
  ['cow', 'O'],
  ['disease', 'O'],
  ['can', 'O'],
  ['be', 'O'],
  ['transmitted', 'O'],
  ['to', 'O'],
  ['sheep', 'O'],
  ['.', 'O']],
 [['Germany', 'LOC'],
  ["'s", 'O'],
  ['representative', 'O'],
  ['to', 'O'],
  ['the', 'O'],
  ['European', 'ORG'],
  ['Union', 'ORG'],
  ["'s", 'O'],
  ['veterinary', 'O'],
  ['committ

In [131]:
import itertools
list(itertools.chain.from_iterable(["ABC","EFG"]))

['A', 'B', 'C', 'E', 'F', 'G']